/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedDriverIndexRouteImport } from './routes/_authenticated/driver/index'
import { Route as AuthenticatedShopIndexRouteImport } from './routes/_authenticated/shop/index'
import { Route as AuthenticatedShopSettingsRouteImport } from './routes/_authenticated/shop/settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDriverIndexRoute =
  AuthenticatedDriverIndexRouteImport.update({
    id: '/driver/',
    path: '/driver/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedShopIndexRoute = AuthenticatedShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedShopSettingsRoute =
  AuthenticatedShopSettingsRouteImport.update({
    id: '/shop/settings',
    path: '/shop/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/terms': typeof TermsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/shop/settings': typeof AuthenticatedShopSettingsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/driver/': typeof AuthenticatedDriverIndexRoute
  '/shop/': typeof AuthenticatedShopIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/terms': typeof TermsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/shop/settings': typeof AuthenticatedShopSettingsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/driver': typeof AuthenticatedDriverIndexRoute
  '/shop': typeof AuthenticatedShopIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/terms': typeof TermsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/shop/settings': typeof AuthenticatedShopSettingsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/driver/': typeof AuthenticatedDriverIndexRoute
  '/_authenticated/shop/': typeof AuthenticatedShopIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/terms'
    | '/onboarding'
    | '/shop/settings'
    | '/admin/'
    | '/driver/'
    | '/shop/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/terms'
    | '/onboarding'
    | '/shop/settings'
    | '/admin'
    | '/driver'
    | '/shop'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/terms'
    | '/_authenticated/onboarding'
    | '/_authenticated/shop/settings'
    | '/_authenticated/admin/'
    | '/_authenticated/driver/'
    | '/_authenticated/shop/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/driver/': {
      id: '/_authenticated/driver/'
      path: '/driver'
      fullPath: '/driver/'
      preLoaderRoute: typeof AuthenticatedDriverIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shop/': {
      id: '/_authenticated/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof AuthenticatedShopIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shop/settings': {
      id: '/_authenticated/shop/settings'
      path: '/shop/settings'
      fullPath: '/shop/settings'
      preLoaderRoute: typeof AuthenticatedShopSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedShopSettingsRoute: typeof AuthenticatedShopSettingsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedDriverIndexRoute: typeof AuthenticatedDriverIndexRoute
  AuthenticatedShopIndexRoute: typeof AuthenticatedShopIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedShopSettingsRoute: AuthenticatedShopSettingsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedDriverIndexRoute: AuthenticatedDriverIndexRoute,
  AuthenticatedShopIndexRoute: AuthenticatedShopIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
